### ISSUE TITLE
error: unable to recognize "STDIN": no matches for kind "ProviderConfig" in version "gcp.crossplane.io/v1beta1"

### ISSUE THREAD

**Issue by ejf-coders51** [crossplane/crossplane#2440]
### What happened?
Error on ProviderConfig deployment

### How can we reproduce it?
Create a cluster
kind create cluster

Install crossplane

kubectl create namespace crossplane-system
helm install crossplane --namespace crossplane-system crossplane-stable/crossplane

Install gcp provider

kubectl crossplane install provider crossplane/provider-gcp:v0.12.0

When i try to deploy the config like this

```
PROJECT_ID=my-project
echo "apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: ${PROJECT_ID}
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-creds
      key: creds" | kubectl apply -f -
```

i receive this error, like the v1beta don't know that type of resource

`error: unable to recognize "STDIN": no matches for kind "ProviderConfig" in version "gcp.crossplane.io/v1beta1"
`

### What environment did it happen in?
Crossplane version: v1.3.0

**Comment by hasheddan** [comment]
@ejf-coders51 upgrading to the latest version of `provider-gcp` should fix the issue :) https://github.com/crossplane/provider-gcp/releases/tag/v0.17.1

**Comment by ejf-coders51** [comment]
i've deleted the cluster and do it again with the provider-gcp:v0.17.1 but the error persist

**Comment by hasheddan** [comment]
@ejf-coders51 can you provide the output of `kubectl desribe provider` and `kubectl describe providerrevision`?

**Comment by ejf-coders51** [comment]
Name:         crossplane-provider-gcp
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  pkg.crossplane.io/v1
Kind:         Provider
Metadata:
  Creation Timestamp:  2021-07-20T07:05:58Z
  Generation:          1
  Managed Fields:
    API Version:  pkg.crossplane.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:ignoreCrossplaneConstraints:
        f:package:
        f:packagePullPolicy:
        f:revisionActivationPolicy:
        f:revisionHistoryLimit:
        f:skipDependencyResolution:
      f:status:
    Manager:         kubectl-crossplane
    Operation:       Update
    Time:            2021-07-20T07:05:58Z
  Resource Version:  848
  UID:               6be4058f-a372-425d-aa64-b80d59162353
Spec:
  Ignore Crossplane Constraints:  false
  Package:                        crossplane/provider-gcp:v0.17.1
  Package Pull Policy:            IfNotPresent
  Revision Activation Policy:     Automatic
  Revision History Limit:         0
  Skip Dependency Resolution:     false
Events:
  Type     Reason         Age                     From                                 Message
  ----     ------         ----                    ----                                 -------
  Warning  UnpackPackage  5m15s (x39 over 5h27m)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: Get "https://index.docker.io/v2/": context deadline exceeded


and  _kubectl describe providerrevision_ the second command return no output

**Comment by hasheddan** [comment]
@ejf-coders51 it appears that you do not have access to dockerhub from inside your cluster. Can you describe your environment?

**Comment by ejf-coders51** [comment]
i've tried with k3d istead of kind and it works. it should be some config of kind.  thaks for the help

**Comment by negz** [comment]
@ejf-coders51 Thanks for letting us know you got this working. I'll close this issue but let us know if there's anything else you need.
